### ISSUE TITLE
Only for Turkish numbers

### ISSUE THREAD

**Issue by ramyberrekia** [farukalpay/SMS-Sender#1]
Please note that this tool is only for **Turkish** numbers.

**Comment by farukalpay** [comment]
Hello, It's still in the development stage. I plan to add other countries as well. However, for the first phase, I will limit it to only Turkey to test and fix any errors. If you tell me the countries you want to be added as a priority, I will note these as feedback. Please stay tuned for other countries.

**Comment by farukalpay** [comment]
I am closing your issue report. Don't hesitate to let me know if you encounter any issue.

**Comment by farukalpay** [comment]
I am closing your issue report. Don't hesitate to let me know if you encounter any problem.
